issues 98 and 99
oripa/oripa pull request #100
Opened 2021-04-24 16:27 UTC by JinoBetti

2021-04-25 11:37 UTC, Ooouch1 requested changes
Build by maven fails since the test of `OriLine::hashCode` fails.

2021-04-25 11:41 UTC, Ooouch1 commented
[heavy_test.zip](https://github.com/oripa/oripa/files/6371824/heavy_test.zip)
A .opx file of 100x100 grid mountain lines with diagonals for performance test.

2021-04-25 17:17 UTC, JinoBetti commented on src/main/java/oripa/domain/cptool/LineAdder.java
> +				.filter(oriLine -> oriLine.getType() != OriLine.Type.CUT)
I changed it before seeing your comment actually, as soon as I saw a method already existed for that 👍 great review tip!

2021-04-25 17:19 UTC, JinoBetti commented on src/main/java/oripa/value/OriLine.java
> +			return this.type.equals(that.type);
fixed, and I also had to fix the mocks from OutlineAdderTest to change the line type for the eq() ArgumentMatcher

2021-04-25 17:31 UTC, JinoBetti commented on src/main/java/oripa/value/OriLine.java
> +		if(isVertical()) return abs(getAffineXValueAt(oriPoint.y) - oriPoint.x) < EPS && rectangleClipper.contains(oriPoint);
Agreed, and fixed 👍

2021-04-25 17:35 UTC, JinoBetti commented
> [heavy_test.zip](https://github.com/oripa/oripa/files/6371950/heavy_test.zip)
> A .opx file of 100x100 grid mountain lines with diagonals for performance test.
> 
> edit: the file was incomplete. I re-uploaded.

wow, that's a lot of lines... do you have the standards of how long it takes with the current version, and how long you find it "acceptable"?, it's long to load but not suprising (~2-3 seconds)... cutting and pasting the whole thing is very long, though (47 seconds), but again... nothing very surprising for something that appears as a big black square due to the number of vertices :)

2021-04-26 10:11 UTC, Ooouch1 requested changes
I got a wrong result:

1. Draw (-100,0, 0,0, V) and (100,0, 200,0, V).
2. Draw (-200,0, 200,0, M).
3. You will get some extra mountain lines. Try deleting the generated lines one by one.

2021-04-26 10:46 UTC, Ooouch1 commented
> do you have the standards of how long it takes with the current version,
> and how long you find it "acceptable"?, it's long to load but not suprising (~2-3 seconds)... cutting and pasting the whole thing is very long, though (47 seconds)

On ver. 1.45, if I cut all lines of heavy_test.opx and paste them, it takes 1~2 seconds with Surface Pro 7 core i5.
Since `OverlappingLineExtractor::extract(lines)` takes around 1 second in this case (you can try this method by running foldability check), I guess there is a way to finish detecting overlapping segments and splitting them in less than 5 seconds on my Surface.
Maybe a faster algorithm is to use a modification of `OverlappingLineExtractor::extract(lines)` to group the segments with the support lines.

By the way, it was good if you made pull requests per issue, a PR for issue 98 and a PR for issue 99, which enables me to merge fix of issue 98 earlier.

2021-04-26 22:26 UTC, JinoBetti commented
it takes ~8 seconds with the old version on my desktop. The overlap detection of each of the 30 000 input lines (squared...) is indeed much too long in comparison :( [900 000 000 iterations in 37484ms] 
I'll see in the next few days if I can find a better way to do it, probably using your idea of grouping by support line. 

The only other solution I can think of is having a reduced functionality mode when adding too many lines at once (When pasting more than 250 lines at once, fall back to the old way for example, since the performance problem is only visible when we have a huge number of input lines and a huge number of existing lines [e.g. : 7 500 000 iterations in 479ms], and I never used than many lines before so I think it wont happen very often)

Anyways, I still have work to do to do it correctly, but I'm sure we'll find a way... ganbarimasu!

2021-12-29 17:51 UTC, lifesbest23 commented
> I got a wrong result:
> 
>     1. Draw (-100,0, 0,0, V) and (100,0, 200,0, V).
> 
>     2. Draw (-200,0, 200,0, M).
> 
>     3. You will get some extra mountain lines. Try deleting the generated lines one by one.

I fixed this issue as well as changed the hashing Function to include `type` here: https://github.com/lifesbest23/oripa/tree/fix/issue98

> the programmer should be aware that producing distinct integer results for unequal objects may improve the performance of hash tables.
> As much as is reasonably practical, the `hashCode `method defined by class `Object` does return distinct integers for distinct objects.

I am not sure if my implementation is better, since it has more distinct hashes for `OriLine`, but it does not improve anything performance wise in my testing, so I am not sure if the previous implementation is preferred.

> On ver. 1.45, if I cut all lines of heavy_test.opx and paste them, it takes 1~2 seconds with Surface Pro 7 core i5.
> Since `OverlappingLineExtractor::extract(lines)` takes around 1 second in this case

The cut paste heavy_test does seem to work as well as in the current master branch after the changes in this PR , at least for me, so I think this is a separate issue.

I am not sure where to make a PR though, either for @JinoBetti s branch, or a new one here?

2021-12-30 09:18 UTC, Ooouch1 commented
@lifesbest23 It seems you have solved the problem of overwriting line type by using "1 new overlapping line vs. n existing lines" case solution. It might be slow if many added lines overlap with existing lines. Is the performance on heavy_test.opx OK if you change the left half of the creases to V and the right half to M, and cut/copy the V lines then paste over M lines?

Your implementation of `OriLine::hashCode` seems to violate the 2nd [condition](https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#hashCode--) of `hashCode()`:
*If two objects are equal according to the equals(Object) method, then calling the hashCode method on each of the two objects must produce the same integer result.*

> I am not sure where to make a PR though, either for @JinoBetti s branch, or a new one here?

I think new PR on this repository will make reviews between you and me easier.

2022-04-10 06:12 UTC, merged